version: "3.3"
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./postgres:/var/lib/postgresql/data:z
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_URL
    env_file:
      - ./.env

